[build]
  publish = "dist"
  command = ""

[[headers]]
  for = "/ebook/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "inline"

[[headers]]
  for = "/ebook/*.epub"
  [headers.values]
    Content-Type = "application/epub+zip"
    Content-Disposition = "attachment"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
